//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.UIFramework.Examples {
    
    
    public sealed class ScreenIds {
        
        public const string TapToPlayWindow = "Prefabs/Screens/TapToPlayWindow";
        
        public const string TapToPlayWindowV = "Prefabs/Screens/TapToPlayWindowV";
    }
}
